'use strict';

// ══ CATÁLOGO PRINCIPAL ════════════════════════════════════════════
const BOOKS = []; // El catálogo ahora vive 100% en Supabase
// ══ NOVEDADES (recientes) ═════════════════════════════════════════
const NEW_RELEASES = [
    {id:101,title:"Tomorrow, and Tomorrow",author:"Gabrielle Zevin",genre:"Ficción",price:21.50,isbn:"0593321200",color:"linear-gradient(135deg,#4a2060,#1a0830)",year:2024,pages:401,rating:4.6,reviews:3421,description:"Sam y Sadie crean un juego que revoluciona la industria. Una historia sobre creatividad, amor y el precio del éxito.",tags:["Contemporánea","Amistad","Arte"]},
    {id:102,title:"Intermezzo",author:"Sally Rooney",genre:"Ficción",price:19.90,isbn:"0374611998",color:"linear-gradient(135deg,#1a3a2a,#081510)",year:2024,pages:448,rating:4.4,reviews:2187,description:"Dos hermanos muy diferentes lidian con el duelo por su padre en la Irlanda contemporánea.",tags:["Contemporánea","Familia","Amor"]},
    {id:103,title:"James",author:"Percival Everett",genre:"Literatura",price:23.00,isbn:"0385550367",color:"linear-gradient(135deg,#3a1a0a,#150800)",year:2024,pages:320,rating:4.8,reviews:4562,description:"Premio Pulitzer 2024. Reimaginación de Huckleberry Finn narrada desde la perspectiva de Jim, el esclavo.",tags:["Premio Pulitzer","Historia","Libertad"]},
    {id:104,title:"The God of the Woods",author:"Lauren Fox",genre:"Thriller",price:20.50,isbn:"0593656844",color:"linear-gradient(135deg,#1a1a4a,#080820)",year:2024,pages:384,rating:4.3,reviews:1876,description:"En un campamento de verano, una adolescente desaparece. Una novela sobre secretos familiares y misterios enterrados.",tags:["Thriller","Misterio","Familia"]},
    {id:105,title:"Orbital",author:"Samantha Harvey",genre:"Ficción",price:18.50,isbn:"0802164056",color:"linear-gradient(135deg,#2a0a3a,#0f0015)",year:2024,pages:209,rating:4.5,reviews:2341,description:"Premio Booker 2024. Seis astronautas orbitan la Tierra durante 24 horas. Una meditación sobre la humanidad.",tags:["Premio Booker","Espacio","Filosófico"]},
    {id:106,title:"The Women",author:"Kristin Hannah",genre:"Literatura",price:22.00,isbn:"1250178630",color:"linear-gradient(135deg,#0a2a1a,#001008)",year:2024,pages:512,rating:4.7,reviews:6789,description:"Vietnam, 1965. Frances McGrath se alista como enfermera. Una historia sobre las mujeres olvidadas de la guerra.",tags:["Guerra","Histórica","Mujeres"]},
    {id:107,title:"All Fours",author:"Miranda July",genre:"Ficción",price:21.00,isbn:"1594634882",color:"linear-gradient(135deg,#2a1a0a,#100800)",year:2024,pages:352,rating:4.2,reviews:1543,description:"Una artista se detiene a 30 minutos de casa. Una novela sobre la identidad femenina, la maternidad y el deseo.",tags:["Contemporánea","Identidad","Mujer"]},
    {id:108,title:"The Anxious Generation",author:"Jonathan Haidt",genre:"No Ficción",price:24.00,isbn:"0593655036",color:"linear-gradient(135deg,#1a2a3a,#080f18)",year:2024,pages:385,rating:4.6,reviews:8234,description:"¿Por qué los índices de depresión juvenil se dispararon alrededor de 2012? Los smartphones causaron una crisis.",tags:["Psicología","Tecnología","Juventud"]}
];

// ══ FALLBACKS — libros adicionales si la API falla ════════════════
const EXTRA_BOOKS_FALLBACK = [
    {id:201,title:"Babel",author:"R.F. Kuang",genre:"Fantasía",subgenre:"Fantasía histórica",price:23.50,originalPrice:32.00,isbn:"0063021420",badge:"Premio Nebula",rating:4.6,reviews:24531,pages:545,language:"Español",publisher:"Hidra",year:2022,color:"linear-gradient(135deg,#3a2a10 0%,#0f0c04 100%)",description:"Oxford, 1836. Robin Swift es llevado del Cantón a Inglaterra para entrenar en el arte de la traducción mágica. Una crítica brillante al colonialismo británico.",shortDesc:"Magia, traducción y revolución en la Oxford colonial.",tags:["Magia","Historia","Colonialismo","Lenguaje"]},
    {id:202,title:"Proyecto Hail Mary",author:"Andy Weir",genre:"Ciencia Ficción",subgenre:"Hard Science Fiction",price:21.90,originalPrice:30.00,isbn:"0593135202",badge:"Bestseller 2021",rating:4.9,reviews:31245,pages:496,language:"Español",publisher:"Nova",year:2021,color:"linear-gradient(135deg,#1a3050 0%,#040c18 100%)",description:"Ryland Grace despierta solo en una nave espacial sin recordar su misión. Pronto descubre que la humanidad depende de él. Del autor de El Marciano.",shortDesc:"La misión imposible para salvar a la humanidad.",tags:["Espacio","Misterio","Primer contacto","Humor"]},
    {id:203,title:"La paciente silenciosa",author:"Alex Michaelides",genre:"Thriller",subgenre:"Thriller psicológico",price:18.50,originalPrice:25.00,isbn:"1250301696",badge:"Bestseller",rating:4.5,reviews:42765,pages:336,language:"Español",publisher:"Alfaguara",year:2019,color:"linear-gradient(135deg,#1a0a25 0%,#080310 100%)",description:"Alicia Berenson dispara cinco veces a su esposo y nunca vuelve a hablar. Un psicoterapeuta obsesionado con su caso intentará desentrañar la verdad.",shortDesc:"El silencio que esconde un crimen perfecto.",tags:["Psicológico","Crimen","Silencio","Giro"]},
    {id:204,title:"Klara y el Sol",author:"Kazuo Ishiguro",genre:"Literatura",subgenre:"Distopía literaria",price:19.90,originalPrice:27.00,isbn:"059331817X",badge:"Premio Nobel",rating:4.4,reviews:18923,pages:303,language:"Español",publisher:"Anagrama",year:2021,color:"linear-gradient(135deg,#3a3010 0%,#100c04 100%)",description:"Klara, una Amiga Artificial, observa el mundo desde el escaparate de una tienda esperando ser elegida. Una meditación sobre el amor y la conciencia.",shortDesc:"Una IA observa el mundo humano desde el escaparate.",tags:["IA","Distopía","Conciencia","Nobel"]},
    {id:205,title:"Cuatro mil semanas",author:"Oliver Burkeman",genre:"No Ficción",subgenre:"Filosofía práctica",price:17.50,originalPrice:24.00,isbn:"0374159122",badge:"Bestseller 2021",rating:4.5,reviews:14532,pages:288,language:"Español",publisher:"Salamandra",year:2021,color:"linear-gradient(135deg,#102a30 0%,#040c0e 100%)",description:"La vida humana es absurdamente corta: cuatro mil semanas. Burkeman propone un enfoque radical sobre el tiempo y la productividad.",shortDesc:"La vida es corta. La filosofía sobre cómo aprovecharla.",tags:["Tiempo","Productividad","Filosofía","Vida"]},
    {id:206,title:"El infinito en un junco",author:"Irene Vallejo",genre:"No Ficción",subgenre:"Historia de la cultura",price:20.50,originalPrice:28.00,isbn:"8417454966",badge:"Premio Nacional",rating:4.8,reviews:22341,pages:452,language:"Español",publisher:"Siruela",year:2019,color:"linear-gradient(135deg,#2a1a0a 0%,#0a0603 100%)",description:"La historia fascinante del libro como objeto, desde las tablillas sumerias hasta nuestros días. Un viaje por la cultura escrita.",shortDesc:"La historia del libro contada como una novela.",tags:["Historia","Libros","Cultura","Ensayo"]}
];
