-- ╔══════════════════════════════════════════════════════════════╗
-- ║  FOLIO — Seed de datos iniciales                             ║
-- ║  Ejecutar DESPUÉS de schema.sql                              ║
-- ║                                                              ║
-- ║  Las contraseñas son hashes bcrypt generados con saltRounds=10║
-- ║                                                              ║
-- ║  admin@folio.com    →  admin123                              ║
-- ║  empleado@folio.com →  empleado123                           ║
-- ║  cliente@folio.com  →  cliente123                            ║
-- ╚══════════════════════════════════════════════════════════════╝

INSERT INTO users (name, email, password_hash, role) VALUES
                                                         ('Administrador Folio', 'admin@folio.com',    '$2b$10$wH1m7l2u3wQk1qe1Y8h0SeJ9o0QdK5J4r2Z0r3uS5y0N7v0R7m9aS', 'admin'),
                                                         ('Empleado Folio',      'empleado@folio.com', '$2b$10$wH1m7l2u3wQk1qe1Y8h0SeJ9o0QdK5J4r2Z0r3uS5y0N7v0R7m9aS', 'employee'),
                                                         ('Cliente Demo',        'cliente@folio.com',  '$2b$10$wH1m7l2u3wQk1qe1Y8h0SeJ9o0QdK5J4r2Z0r3uS5y0N7v0R7m9aS', 'client')
    ON CONFLICT (email) DO NOTHING;

-- Los hashes anteriores son placeholders. El servidor genera los hashes
-- reales al primer arranque (ver server/db.js → ensureSeedUsers).

INSERT INTO books (title, author, genre, subgenre, price, original_price, isbn, description, short_desc, publisher, year, pages, language, rating, reviews, stock, badge, cover_color) VALUES
                                                                                                                                                                                           ('El nombre del viento', 'Patrick Rothfuss', 'Fantasía', 'Fantasía épica', 22.90, 32.00, '0756404746', 'Kvothe, el mago más temido de su época, ahora posadero, relata su vida durante tres días.', 'Una historia dentro de la historia.', 'DAW Books', 2007, 662, 'Español', 4.6, 12450, 50, 'Bestseller', 'linear-gradient(135deg,#8B2635 0%,#2d0a10 100%)'),
                                                                                                                                                                                           ('El temor de un hombre sabio', 'Patrick Rothfuss', 'Fantasía', 'Fantasía épica', 24.50, 30.00, '0756407125', 'Segunda jornada de la crónica del asesino de reyes.', 'La continuación de Kvothe.', 'DAW Books', 2011, 994, 'Español', 4.5, 9870, 40, 'Saga', 'linear-gradient(135deg,#3a1a5c 0%,#0f0820 100%)'),
                                                                                                                                                                                           ('Mistborn: El imperio final', 'Brandon Sanderson', 'Fantasía', 'Fantasía heroica', 19.90, 26.00, '0765311780', 'En un mundo dominado por un Lord Legislador inmortal, una joven descubre que puede usar magia.', 'Magia con metales y rebelión.', 'Tor Books', 2006, 541, 'Español', 4.7, 15300, 60, 'Saga', 'linear-gradient(135deg,#2a1a4a 0%,#0a0820 100%)'),
                                                                                                                                                                                           ('Dune', 'Frank Herbert', 'Ciencia Ficción', 'Space opera', 21.00, 28.00, '0441013597', 'En el desértico planeta Arrakis, Paul Atreides debe sobrevivir a una conspiración interplanetaria.', 'La obra magna de la ciencia ficción.', 'Debolsillo', 1965, 688, 'Español', 4.8, 22100, 70, 'Clásico', 'linear-gradient(135deg,#c9651e 0%,#3a1d08 100%)'),
                                                                                                                                                                                           ('Fundación', 'Isaac Asimov', 'Ciencia Ficción', 'Hard SF', 18.50, 24.00, '0553293354', 'Hari Seldon predice la caída del Imperio Galáctico y crea la Fundación para preservar el conocimiento.', 'Psicohistoria y galaxia.', 'Debolsillo', 1951, 296, 'Español', 4.6, 14200, 55, 'Clásico', 'linear-gradient(135deg,#0a2a4a 0%,#04101c 100%)'),
                                                                                                                                                                                           ('Neuromante', 'William Gibson', 'Ciencia Ficción', 'Cyberpunk', 17.90, 22.00, '0441569595', 'Case, un hacker quemado, recibe una última oportunidad: el trabajo más peligroso de su vida.', 'El nacimiento del cyberpunk.', 'Minotauro', 1984, 320, 'Español', 4.4, 8900, 35, 'Cyberpunk', 'linear-gradient(135deg,#0a1a3a 0%,#02080f 100%)'),
                                                                                                                                                                                           ('La chica del tren', 'Paula Hawkins', 'Thriller', 'Thriller psicológico', 16.90, 22.00, '1594634025', 'Rachel ve algo desde el tren cada mañana. Hasta que un día descubre algo aterrador.', 'Suspense que atrapa.', 'Planeta', 2015, 410, 'Español', 4.2, 18500, 45, 'Bestseller', 'linear-gradient(135deg,#1a0a25 0%,#080310 100%)'),
                                                                                                                                                                                           ('Perdida', 'Gillian Flynn', 'Thriller', 'Thriller psicológico', 18.90, 24.00, '0307588378', 'En su quinto aniversario, la mujer de Nick Dunne desaparece sin dejar rastro.', 'Una pareja, dos versiones.', 'Random House', 2012, 432, 'Español', 4.5, 21300, 50, 'Best.', 'linear-gradient(135deg,#1a0505 0%,#080202 100%)'),
                                                                                                                                                                                           ('El silencio de los corderos', 'Thomas Harris', 'Thriller', 'Thriller criminal', 17.50, 23.00, '0312924585', 'La agente Clarice Starling necesita la ayuda del Dr. Hannibal Lecter para atrapar a un asesino.', 'Hannibal Lecter.', 'RBA', 1988, 448, 'Español', 4.7, 19800, 40, 'Clásico', 'linear-gradient(135deg,#251005 0%,#0a0402 100%)'),
                                                                                                                                                                                           ('Cien años de soledad', 'Gabriel García Márquez', 'Literatura', 'Realismo mágico', 19.50, 25.00, '0307474720', 'La saga familiar de los Buendía a través de siete generaciones en Macondo.', 'Realismo mágico.', 'Sudamericana', 1967, 471, 'Español', 4.9, 32500, 60, 'Clásico', 'linear-gradient(135deg,#3a2a1a 0%,#100a04 100%)'),
                                                                                                                                                                                           ('1984', 'George Orwell', 'Literatura', 'Distopía', 15.90, 20.00, '0451524934', 'Winston Smith vive en un mundo donde el Gran Hermano lo vigila todo.', 'Distopía y vigilancia.', 'Debolsillo', 1949, 328, 'Español', 4.8, 28700, 65, 'Clásico', 'linear-gradient(135deg,#1a1a1a 0%,#080808 100%)'),
                                                                                                                                                                                           ('El principito', 'Antoine de Saint-Exupéry', 'Literatura', 'Cuento filosófico', 12.50, 16.00, '0156012197', 'Un piloto perdido en el desierto se encuentra con un pequeño príncipe de otro planeta.', 'Para todas las edades.', 'Salamandra', 1943, 96, 'Español', 4.9, 41200, 100, 'Clásico', 'linear-gradient(135deg,#5a4a1a 0%,#1a1408 100%)'),
                                                                                                                                                                                           ('Sapiens', 'Yuval Noah Harari', 'No Ficción', 'Historia', 22.00, 28.00, '0062316097', 'De animales insignificantes a amos del mundo: una breve historia de la humanidad.', 'Historia universal.', 'Debate', 2011, 496, 'Español', 4.7, 25600, 55, 'Bestseller', 'linear-gradient(135deg,#2a2010 0%,#0a0804 100%)'),
                                                                                                                                                                                           ('Hábitos atómicos', 'James Clear', 'No Ficción', 'Desarrollo personal', 18.90, 24.00, '0735211299', 'Pequeños cambios producen resultados extraordinarios.', 'Cambios pequeños, resultados grandes.', 'Diana', 2018, 320, 'Español', 4.8, 33400, 70, 'Best.', 'linear-gradient(135deg,#1a2a10 0%,#040804 100%)'),
                                                                                                                                                                                           ('El poder del ahora', 'Eckhart Tolle', 'No Ficción', 'Espiritualidad', 16.50, 22.00, '1577314808', 'Una guía hacia la iluminación espiritual a través del momento presente.', 'Conciencia plena.', 'Grijalbo', 1997, 256, 'Español', 4.5, 18200, 45, 'Clásico', 'linear-gradient(135deg,#10202a 0%,#040810 100%)');